spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:sfpdb
    username: sa
    password:
# To See H2 Console in Browser:
# http://localhost:8080/h2-console
# Enabling H2 Console
  h2:
    console:
      enabled: true
      path: /h2-console