spring:
  profiles:
    active: test
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

server:
  error:
    whitelabel:
      enabled: false
  tomcat:
    remote_ip_header: x-forwarded-for
    protocol_header: x-forwarded-proto

server-properties:
  scheme: http
  host: localhost