spring:
  profiles:
    active: test
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

server:
  error:
    whitelabel:
      enabled: false
  tomcat:
    remote_ip_header: x-forwarded-for
    protocol_header: x-forwarded-proto
  servlet:
    session:
      timeout: 4320m
      cookie:
        max-age: 4320m

server-properties:
  scheme: http
  host: localhost